config/routes.rb
NewBlockCity::Application.routes.draw do
  devise_for :users,
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :api do
    resources :worlds do
      resources :regions
    end

    resources :users, only: [] do
      member do
        get :photo
      end
    end

    resources :neighborhoods, only: :index do
      member do
        get :neighbors
      end
    end

    resources :blocks
    resources :panda_videos do
      collection do
        post :callback
      end
    end
  end

  resource :admin, controller: :admin, only: :show do
    member do
      get :test
    end
  end

  namespace :admin do
    resources :blocks
    resources :panda_videos
  end

  namespace :client do
    resources :blocks, only: :create
  end

  # For CORS (Cross Origin Resource Sharing)
  match '/client/blocks',
    :controller => 'client/blocks',
    :action => 'options',
    :constraints => {:method => 'OPTIONS'}

  resources :partials, only: :show

  # Explicitly mount Jasminerice above global match rule to prevent trumping of jasmine
  mount Jasminerice::Engine => "/jasmine" if Rails.env.development? || Rails.env.test?
  match '/' => 'spine#index'
  match '/neighborhoods/(*other)' => 'spine#index'
  match '/regions/(*other)' => 'spine#index'
end

app/controllers/partials_controller.rb
class PartialsController < ApplicationController
  def show
    render partial: "partials/#{params[:id]}"
  end
end

app/views/partials/_block_video_form.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
  %h3#myModalLabel Add Video Block

= simple_form_for [:api, Block::Video.new], url: api_blocks_path do |f|
  .modal-body
    = f.input :type, as: :hidden

    / the control will appear next to this, and the video ID will be stored here after the upload
    %input{name: :panda_id, id: :returned_video_id, type: :hidden}

    / upload progress bar (optional)
    #upload_progress.panda_upload_progress

    = f.label "Longitude"
    %input{:name => "longitude", :type => "number", step: "any"}/

    = f.label "Latitude"
    %input{:name => "latitude", :type => "number", step: "any"}/

    %p
      Please note that it will take a minute for the video to encode
      before appearing on the map

  .modal-footer
    = f.button :submit, class: "btn btn-primary"

- access_details = Panda.signed_params('POST', '/videos.json')
:javascript
  var panda_access_details = #{access_details.to_json.html_safe};

  var successCallback = function(event) {
    $("#addBlockModal form").ajaxSubmit({
      error: function() { console.warn("Unable to submit form"); },
      success: function() { $("#addBlockModal").modal('hide'); }
    });
    return false;
  };

  $("#returned_video_id").pandaUploader(panda_access_details, {
    upload_progress_id: 'upload_progress',
    upload_strategy: new PandaUploader.UploadOnSubmitAjax(successCallback)
  });